name: Publish JavaDocs as HTML

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    # 1️⃣ 签出
    - uses: actions/checkout@v4

    # 2️⃣ 安装 pandoc
    - name: Install Pandoc
      run: choco install pandoc -y

    # 3️⃣ 渲染并复制
    - name: Build site
      shell: pwsh
      run: |
        $srcRoot  = "DrcomoCoreLib/JavaDocs"     # ← 只写一次
        $siteRoot = "site/JavaDocs"              # 目标同名目录
        Remove-Item site -Recurse -Force -EA SilentlyContinue
        New-Item $siteRoot -ItemType Directory -Force | Out-Null

        # 渲染 MD ➜ HTML
        Get-ChildItem -Path $srcRoot -Filter *.md -Recurse | ForEach-Object {
          $rel = $_.FullName.Substring((Get-Item $srcRoot).FullName.Length + 1)
          $out = Join-Path $siteRoot ($rel -replace '\.md$','.html')
          New-Item -ItemType Directory -Force -Path (Split-Path $out) | Out-Null
          pandoc $_.FullName -s -o $out --metadata title=$($_.BaseName)
        }

        # 拷贝原始 MD（可选，不需要就删掉）
        Copy-Item -Recurse $srcRoot\* $siteRoot/ -Force

        # 渲染根 index.md
        $indexSrc = "DrcomoCoreLib/index.md"
        pandoc $indexSrc -s -o "site/index.html" --metadata title="DrcomoCoreLib JavaDocs"
        Copy-Item $indexSrc site/index.md -Force

    # 4️⃣ 禁用 Jekyll
    - name: Create .nojekyll
      shell: pwsh
      run: New-Item site/.nojekyll -ItemType File | Out-Null

    # 5️⃣ 发布
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./site
        force_orphan: true
