name: Publish JavaDocs

on:
  push:
    branches: [ main ]      # main 任意提交触发
  workflow_dispatch:        # 支持手动触发

permissions:
  contents: write           # 允许推 gh-pages

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # 1️⃣ 拉代码
      - uses: actions/checkout@v4

      # 2️⃣ 复制 JavaDocs 到 site 根
      - name: Copy JavaDocs
        shell: pwsh
        run: |
          Remove-Item site -Recurse -Force -EA SilentlyContinue
          New-Item site -ItemType Directory | Out-Null
          Copy-Item -Recurse "DrcomoCoreLib/JavaDocs\*" site/ -Force
          New-Item site/.nojekyll -ItemType File | Out-Null   # 禁用 Jekyll

      # 3️⃣ 推送到 gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages    # <── 显式指定
          publish_dir: ./site
          force_orphan: true
