name: Publish JavaDocs

# ───── 触发条件 ─────
on:
  push:
    branches: [ main ]        # main 分支任何提交都会触发
  workflow_dispatch:          # 允许在网页 Actions → Run workflow 手动触发

# ───── 权限：允许推送 gh-pages ─────
permissions:
  contents: write

# ───── 作业定义 ─────
jobs:
  deploy:
    runs-on: windows-latest    # 遵从你的 Windows 偏好

    steps:
      # 1️⃣ 拉代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ （可选）如需自动生成 index.md，可在此调用脚本
      # - name: Generate index.md
      #   shell: pwsh
      #   run: ./scripts/gen-index.ps1

      # 3️⃣ 复制 JavaDocs 到发布目录
      - name: Copy JavaDocs to publish dir
        shell: pwsh
        run: |
          Remove-Item site -Recurse -Force -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path site | Out-Null
          Copy-Item -Recurse "DrcomoCoreLib/JavaDocs\*" site/ -Force

      # 4️⃣ 发布到 gh-pages（启用 Jekyll 渲染）
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
          enable_jekyll: true        # ← 关键！允许 GitHub 渲染 Markdown
