name: Publish JavaDocs as HTML with README

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    # 1️⃣ 签出代码
    - uses: actions/checkout@v4

    # 2️⃣ 安装 Pandoc
    - name: Install Pandoc
      run: choco install pandoc -y
    # 3️⃣ 构建站点，渲染文档
    - name: Build site
      shell: pwsh
      run: |
        $srcDocs  = "DrcomoCoreLib/JavaDocs"
        $siteDocs = "site/JavaDocs"

        # 清空旧站点
        Remove-Item site -Recurse -Force -EA SilentlyContinue

        # 重建 docs 子目录
        New-Item -ItemType Directory -Path $siteDocs -Force | Out-Null

        # 渲染子目录 .md → .html
        Get-ChildItem -Path $srcDocs -Filter *.md -Recurse | ForEach-Object {
          $rel     = $_.FullName.Substring((Get-Item $srcDocs).FullName.Length + 1)
          $outHtml = Join-Path $siteDocs ($rel -replace '\.md$','.html')
          New-Item -ItemType Directory -Force -Path (Split-Path $outHtml) | Out-Null
          pandoc $_.FullName -s -o $outHtml --metadata title=$($_.BaseName)
        }

        # 复制原始 Markdown
        Copy-Item -Recurse $srcDocs\* $siteDocs/ -Force

        # 根目录改用 README.md 代替 index.md
        $readmeSrc = "DrcomoCoreLib/README.md"
        # 如果需要渲染 README.md 为首页
        pandoc $readmeSrc -s -o "site/index.html" --metadata title="DrcomoCoreLib JavaDocs"
        # 把源 README.md 拷贝到站点根，作为首页源码
        Copy-Item $readmeSrc site/README.md -Force

        # **不再**尝试删除 index.md

    # 4️⃣ 禁用 Jekyll
    - name: Disable Jekyll
      shell: pwsh
      run: New-Item site/.nojekyll -ItemType File | Out-Null

    # 5️⃣ 发布到 gh-pages
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./site
        force_orphan: true
