name: Publish JavaDocs

# ───── 触发条件 ─────
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# ───── 权限：允许推送 gh-pages ─────
permissions:
  contents: write

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # 1️⃣ 拉取源码
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ 清理旧的 site 目录，复制 JavaDocs 下所有 .md 到 site 根
      - name: Copy JavaDocs to site/
        shell: pwsh
        run: |
          Remove-Item site -Recurse -Force -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path site | Out-Null
          Copy-Item -Recurse "DrcomoCoreLib/JavaDocs\*" site/ -Force

      # 3️⃣ 创建 .nojekyll，禁用 Jekyll，让 .md 作为静态资源直接暴露
      - name: Create .nojekyll
        shell: pwsh
        run: New-Item -Path site/.nojekyll -ItemType File | Out-Null

      # 4️⃣ 发布到 gh-pages 分支
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
