name: Publish JavaDocs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # 1️⃣ 拉代码
      - uses: actions/checkout@v4

      # 2️⃣ 安装 Pandoc（用于 md → html）
      - name: Install Pandoc
        run: choco install pandoc -y

      # 3️⃣ 清理旧目录，准备 site
      - name: Prepare site directory
        shell: pwsh
        run: |
          Remove-Item site -Recurse -Force -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path site | Out-Null

      # 4️⃣ 转换所有 JavaDocs 下的 md 为 html 并输出到 site 根
      - name: Convert Markdown to HTML
        shell: pwsh
        run: |
          Get-ChildItem DrcomoCoreLib/JavaDocs -Filter '*.md' -File | ForEach-Object {
            $in = $_.FullName
            $base = $_.BaseName
            # 生成 HTML 路径：site/<basename>.html
            $out = "site\$($base).html"
            pandoc $in -s -o $out --metadata title="$base"
          }

      # 5️⃣ （可选）生成首页 index.html
      - name: Generate homepage
        shell: pwsh
        run: |
          @"
          <!DOCTYPE html>
          <html>
          <head><meta charset="utf-8"><title>DrcomoCoreLib JavaDocs</title></head>
          <body>
            <h1>DrcomoCoreLib JavaDocs</h1>
            <ul>
          "@ > site/index.html
          Get-ChildItem site -Filter '*.html' -File | ForEach-Object {
            $name = $_.BaseName
            Add-Content site/index.html "<li><a href='$($_.Name)'>$name</a></li>"
          }
          Add-Content site/index.html "</ul></body></html>"

      # 6️⃣ 发布到 gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          force_orphan: true
