name: Release DrcomoCoreLib

on:
  push:
    tags:
      - 'v*'  

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: 签出代码
        uses: actions/checkout@v4

      - name: 设置 JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 构建并读取版本
        id: build_and_version
        run: |
          mvn package -DskipTests
          # 提取 project.version
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: 创建 Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: DrcomoCoreLib ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: 上传 Jar 资产
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/DrcomoCoreLib-${{ env.VERSION }}.jar
          asset_name: DrcomoCoreLib-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive
