name: Release DrcomoCoreLib

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: 签出代码
        uses: actions/checkout@v4

      - name: 设置 JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 构建并提取版本
        id: build
        run: |
          mvn package -DskipTests
          VER=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VER=$VER" >> $GITHUB_ENV

      - name: 创建 Release
        id: create_rel
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: 上传 Jar
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_rel.outputs.upload_url }}
          asset_path: target/DrcomoCoreLib-${{ env.VER }}.jar
          asset_name: DrcomoCoreLib-${{ env.VER }}.jar
          asset_content_type: application/java-archive
