name: Upload local-built Jar
on:
  push:
    tags:
      - 'v*'          # 仅 Tag 触发

permissions:
  contents: write      # 生成 Release 需写权限

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # 查找第一个非 original- 前缀的 jar
      - name: Detect jar
        id: jar
        shell: pwsh
        run: |
          $jar = Get-ChildItem target\*.jar |
                 Where-Object Name -NotMatch '^original-' |
                 Select-Object -First 1 -ExpandProperty FullName;
          echo "JAR_PATH=$jar" >> $Env:GITHUB_ENV

      # 发布 Release 并上传刚找到的 Jar
      - name: Publish release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.JAR_PATH }}
